import { ActivityItem } from './activityTypes';

const now = new Date('2026-04-26T09:29:08');
const minsAgo = (m: number) => new Date(now.getTime() - m * 60000).toISOString();

export const mockActivities: ActivityItem[] = [
  {
    id: 'act-001',
    type: 'task_completed',
    actor: { id: 'member-002', name: 'Budi Hartono', avatar: 'BH', role: 'spv' },
    description: 'marked task as Done',
    taskRef: { id: 'task-005', title: 'Set up GoWa WhatsApp microservice on Coolify' },
    project: 'Infrastructure',
    timestamp: minsAgo(4),
    waSent: true,
    gotifyPushed: true,
  },
  {
    id: 'act-002',
    type: 'status_changed',
    actor: { id: 'member-003', name: 'Citra Dewi', avatar: 'CD', role: 'employee' },
    description: 'moved task to Under Review',
    taskRef: { id: 'task-001', title: 'Redesign onboarding flow for mobile app' },
    project: 'Mobile App',
    timestamp: minsAgo(11),
    waSent: false,
    gotifyPushed: true,
  },
  {
    id: 'act-003',
    type: 'task_created',
    actor: { id: 'member-001', name: 'Andi Susanto', avatar: 'AS', role: 'manager' },
    description: 'created and assigned a new task',
    taskRef: { id: 'task-010', title: 'Design system documentation — component library' },
    project: 'Mobile App',
    timestamp: minsAgo(18),
    waSent: true,
    gotifyPushed: true,
  },
  {
    id: 'act-004',
    type: 'task_overdue',
    actor: { id: 'member-004', name: 'Dimas Pratama', avatar: 'DP', role: 'employee' },
    description: 'has an overdue task — WA reminder sent',
    taskRef: { id: 'task-002', title: 'Fix payment gateway timeout on checkout' },
    project: 'E-Commerce Platform',
    timestamp: minsAgo(22),
    waSent: true,
    gotifyPushed: true,
  },
  {
    id: 'act-005',
    type: 'comment_added',
    actor: { id: 'member-005', name: 'Eka Wulandari', avatar: 'EW', role: 'spv' },
    description: 'added a comment on task',
    taskRef: { id: 'task-003', title: 'Q2 marketing campaign asset preparation' },
    project: 'Marketing Q2',
    timestamp: minsAgo(35),
    waSent: false,
    gotifyPushed: false,
    meta: { comment: 'Assets for Instagram should be 1:1 ratio, please check the brand guide.' },
  },
  {
    id: 'act-006',
    type: 'file_uploaded',
    actor: { id: 'member-006', name: 'Farhan Rizki', avatar: 'FR', role: 'employee' },
    description: 'uploaded 2 files to task',
    taskRef: { id: 'task-006', title: 'Sales pipeline review — Surabaya region' },
    project: 'Sales',
    timestamp: minsAgo(47),
    waSent: false,
    gotifyPushed: true,
    meta: { files: 'Q1_Surabaya_Pipeline.xlsx, Regional_Targets.pdf' },
  },
  {
    id: 'act-007',
    type: 'task_assigned',
    actor: { id: 'member-001', name: 'Andi Susanto', avatar: 'AS', role: 'manager' },
    description: 'assigned task to Gita Permata',
    taskRef: { id: 'task-004', title: 'Monthly financial report — April 2026' },
    project: 'Finance',
    timestamp: minsAgo(63),
    waSent: true,
    gotifyPushed: true,
  },
  {
    id: 'act-008',
    type: 'status_changed',
    actor: { id: 'member-004', name: 'Dimas Pratama', avatar: 'DP', role: 'employee' },
    description: 'started working on task',
    taskRef: { id: 'task-007', title: 'Implement RLS policies on Supabase user tables' },
    project: 'Infrastructure',
    timestamp: minsAgo(78),
    waSent: false,
    gotifyPushed: true,
  },
  {
    id: 'act-009',
    type: 'task_updated',
    actor: { id: 'member-007', name: 'Gita Permata', avatar: 'GP', role: 'employee' },
    description: 'updated task due date and description',
    taskRef: { id: 'task-004', title: 'Monthly financial report — April 2026' },
    project: 'Finance',
    timestamp: minsAgo(95),
    waSent: false,
    gotifyPushed: false,
  },
  {
    id: 'act-010',
    type: 'wa_sent',
    actor: { id: 'member-001', name: 'Andi Susanto', avatar: 'AS', role: 'manager' },
    description: 'GoWa sent automated deadline reminder via WhatsApp',
    taskRef: { id: 'task-002', title: 'Fix payment gateway timeout on checkout' },
    project: 'E-Commerce Platform',
    timestamp: minsAgo(112),
    waSent: true,
    gotifyPushed: false,
    meta: { recipient: 'Dimas Pratama', phone: '+62 812-xxxx-3421' },
  },
  {
    id: 'act-011',
    type: 'task_completed',
    actor: { id: 'member-005', name: 'Eka Wulandari', avatar: 'EW', role: 'spv' },
    description: 'marked task as Done',
    taskRef: { id: 'task-011', title: 'Customer support SLA audit — March responses' },
    project: 'Customer Success',
    timestamp: minsAgo(130),
    waSent: true,
    gotifyPushed: true,
  },
  {
    id: 'act-012',
    type: 'task_created',
    actor: { id: 'member-002', name: 'Budi Hartono', avatar: 'BH', role: 'spv' },
    description: 'created a new critical task',
    taskRef: { id: 'task-009', title: 'Gotify push notification integration test' },
    project: 'Infrastructure',
    timestamp: minsAgo(155),
    waSent: true,
    gotifyPushed: true,
  },
  {
    id: 'act-013',
    type: 'chat_message',
    actor: { id: 'member-008', name: 'Hendra Wijaya', avatar: 'HW', role: 'ceo' },
    description: 'sent a message in #general',
    project: undefined,
    timestamp: minsAgo(172),
    waSent: false,
    gotifyPushed: false,
    meta: { channel: '#general', preview: 'Let\'s sync on the Q2 roadmap this Friday.' },
  },
  {
    id: 'act-014',
    type: 'file_uploaded',
    actor: { id: 'member-007', name: 'Gita Permata', avatar: 'GP', role: 'employee' },
    description: 'uploaded April budget draft',
    taskRef: { id: 'task-004', title: 'Monthly financial report — April 2026' },
    project: 'Finance',
    timestamp: minsAgo(198),
    waSent: false,
    gotifyPushed: false,
    meta: { files: 'April_2026_Budget_Draft_v2.xlsx' },
  },
  {
    id: 'act-015',
    type: 'task_assigned',
    actor: { id: 'member-001', name: 'Andi Susanto', avatar: 'AS', role: 'manager' },
    description: 'reassigned task to Budi Hartono',
    taskRef: { id: 'task-009', title: 'Gotify push notification integration test' },
    project: 'Infrastructure',
    timestamp: minsAgo(240),
    waSent: true,
    gotifyPushed: true,
  },
];

export const mockSummary = {
  activeMembers: 6,
  tasksUpdated: 9,
  completions: 2,
  waRemindersSent: 5,
  overdueAlerts: 2,
};