import { ChatChannel, ChatMessage, ChatMember } from './chatTypes';

const now = new Date('2026-04-26T09:29:08');
const minsAgo = (m: number) => new Date(now.getTime() - m * 60000).toISOString();

export const mockMembers: ChatMember[] = [
  { id: 'member-001', name: 'Andi Susanto', avatar: 'AS', role: 'Manager', online: true },
  { id: 'member-002', name: 'Budi Hartono', avatar: 'BH', role: 'SPV', online: true },
  { id: 'member-003', name: 'Citra Dewi', avatar: 'CD', role: 'Employee', online: true, lastSeen: 'Active now' },
  { id: 'member-004', name: 'Dimas Pratama', avatar: 'DP', role: 'Employee', online: false, lastSeen: '22 min ago' },
  { id: 'member-005', name: 'Eka Wulandari', avatar: 'EW', role: 'SPV', online: false, lastSeen: '1 hr ago' },
  { id: 'member-006', name: 'Farhan Rizki', avatar: 'FR', role: 'Employee', online: false, lastSeen: '2 hr ago' },
  { id: 'member-007', name: 'Gita Permata', avatar: 'GP', role: 'Employee', online: false, lastSeen: '3 hr ago' },
  { id: 'member-008', name: 'Hendra Wijaya', avatar: 'HW', role: 'CEO', online: false, lastSeen: 'Yesterday' },
];

export const mockChannels: ChatChannel[] = [
  {
    id: 'ch-general',
    name: 'general',
    type: 'channel',
    description: 'Company-wide announcements and general discussion',
    memberCount: 8,
    unreadCount: 3,
    lastMessage: 'Let\'s sync on the Q2 roadmap this Friday.',
    lastMessageTime: minsAgo(172),
    waBridge: false,
    members: mockMembers,
  },
  {
    id: 'ch-engineering',
    name: 'engineering',
    type: 'channel',
    description: 'Backend, frontend, and infrastructure team',
    memberCount: 4,
    unreadCount: 7,
    lastMessage: 'RLS policies are deployed to staging ✓',
    lastMessageTime: minsAgo(18),
    waBridge: true,
    members: mockMembers.filter((m) => ['member-002', 'member-004', 'member-001'].includes(m.id)),
  },
  {
    id: 'ch-marketing',
    name: 'marketing',
    type: 'channel',
    description: 'Campaigns, assets, and growth initiatives',
    memberCount: 3,
    unreadCount: 0,
    lastMessage: 'Instagram assets uploaded to docs folder.',
    lastMessageTime: minsAgo(95),
    waBridge: false,
    members: mockMembers.filter((m) => ['member-005', 'member-001'].includes(m.id)),
  },
  {
    id: 'ch-infrastructure',
    name: 'infra-ops',
    type: 'channel',
    description: 'Coolify, Docker, Supabase, GoWa operations',
    memberCount: 3,
    unreadCount: 2,
    lastMessage: 'Gotify container restarted — all push notifications normal.',
    lastMessageTime: minsAgo(45),
    waBridge: true,
    members: mockMembers.filter((m) => ['member-002', 'member-004', 'member-001'].includes(m.id)),
  },
  {
    id: 'dm-budi',
    name: 'Budi Hartono',
    type: 'dm',
    unreadCount: 1,
    lastMessage: 'Can you review the RLS PR when you get a chance?',
    lastMessageTime: minsAgo(35),
    waBridge: false,
    online: true,
    members: [mockMembers[1]],
  },
  {
    id: 'dm-citra',
    name: 'Citra Dewi',
    type: 'dm',
    unreadCount: 0,
    lastMessage: 'Sent the mockups to your email too.',
    lastMessageTime: minsAgo(130),
    waBridge: false,
    online: true,
    members: [mockMembers[2]],
  },
  {
    id: 'dm-hendra',
    name: 'Hendra Wijaya',
    type: 'dm',
    unreadCount: 0,
    lastMessage: 'Great work on the Q1 targets.',
    lastMessageTime: minsAgo(480),
    waBridge: false,
    online: false,
    members: [mockMembers[7]],
  },
];

export const mockMessages: Record<string, ChatMessage[]> = {
  'ch-engineering': [
    {
      id: 'msg-eng-001',
      channelId: 'ch-engineering',
      senderId: 'member-002',
      senderName: 'Budi Hartono',
      senderAvatar: 'BH',
      senderRole: 'SPV',
      content: 'Morning team! Deploying the RLS policies to staging now. Will ping once done.',
      timestamp: minsAgo(85),
      status: 'read',
      reactions: [{ emoji: '👍', count: 2, byMe: true }],
      isMe: false,
    },
    {
      id: 'msg-eng-002',
      channelId: 'ch-engineering',
      senderId: 'member-004',
      senderName: 'Dimas Pratama',
      senderAvatar: 'DP',
      senderRole: 'Employee',
      content: 'I\'ll be testing the payment gateway fix in parallel. The 30s timeout was traced to a missing connection pool config.',
      timestamp: minsAgo(78),
      status: 'read',
      reactions: [],
      isMe: false,
    },
    {
      id: 'msg-eng-003',
      channelId: 'ch-engineering',
      senderId: 'member-001',
      senderName: 'Andi Susanto',
      senderAvatar: 'AS',
      senderRole: 'Manager',
      content: 'Good catch Dimas. Make sure to update the task status once it\'s confirmed fixed — GoWa will auto-notify the stakeholders.',
      timestamp: minsAgo(72),
      status: 'read',
      reactions: [{ emoji: '✅', count: 1, byMe: false }],
      isMe: true,
    },
    {
      id: 'msg-eng-004',
      channelId: 'ch-engineering',
      senderId: 'member-002',
      senderName: 'Budi Hartono',
      senderAvatar: 'BH',
      senderRole: 'SPV',
      content: 'RLS policies are deployed to staging ✓',
      timestamp: minsAgo(18),
      status: 'read',
      reactions: [{ emoji: '🎉', count: 3, byMe: true }, { emoji: '🔥', count: 1, byMe: false }],
      isMe: false,
    },
    {
      id: 'msg-eng-005',
      channelId: 'ch-engineering',
      senderId: 'member-001',
      senderName: 'Andi Susanto',
      senderAvatar: 'AS',
      senderRole: 'Manager',
      content: 'Perfect. Can you open a PR for review? I\'ll assign Dimas as reviewer.',
      timestamp: minsAgo(15),
      status: 'delivered',
      reactions: [],
      isMe: true,
    },
    {
      id: 'msg-eng-006',
      channelId: 'ch-engineering',
      senderId: 'member-002',
      senderName: 'Budi Hartono',
      senderAvatar: 'BH',
      senderRole: 'SPV',
      content: 'PR is up. Also — Gotify container had a brief restart at 08:45, all push notifications are normal now.',
      timestamp: minsAgo(12),
      status: 'read',
      reactions: [],
      attachments: [{ name: 'rls-policy-diff.png', size: '184 KB', type: 'image' }],
      isMe: false,
    },
    {
      id: 'msg-eng-007',
      channelId: 'ch-engineering',
      senderId: 'member-001',
      senderName: 'Andi Susanto',
      senderAvatar: 'AS',
      senderRole: 'Manager',
      content: 'Thanks for the heads up. Let\'s do a full end-to-end test this afternoon: task update → Supabase webhook → GoWa → WA delivery.',
      timestamp: minsAgo(8),
      status: 'delivered',
      reactions: [],
      isMe: true,
    },
  ],
  'ch-general': [
    {
      id: 'msg-gen-001',
      channelId: 'ch-general',
      senderId: 'member-008',
      senderName: 'Hendra Wijaya',
      senderAvatar: 'HW',
      senderRole: 'CEO',
      content: 'Good morning team! Great execution last week. Q1 targets were hit across all departments.',
      timestamp: minsAgo(210),
      status: 'read',
      reactions: [{ emoji: '🙌', count: 5, byMe: true }, { emoji: '💪', count: 3, byMe: false }],
      isMe: false,
    },
    {
      id: 'msg-gen-002',
      channelId: 'ch-general',
      senderId: 'member-001',
      senderName: 'Andi Susanto',
      senderAvatar: 'AS',
      senderRole: 'Manager',
      content: 'Congrats everyone! Reminder that Q2 planning starts this week. Please update your task estimates by EOD Thursday.',
      timestamp: minsAgo(195),
      status: 'read',
      reactions: [{ emoji: '👍', count: 4, byMe: false }],
      isMe: true,
    },
    {
      id: 'msg-gen-003',
      channelId: 'ch-general',
      senderId: 'member-008',
      senderName: 'Hendra Wijaya',
      senderAvatar: 'HW',
      senderRole: 'CEO',
      content: 'Let\'s sync on the Q2 roadmap this Friday.',
      timestamp: minsAgo(172),
      status: 'read',
      reactions: [],
      isMe: false,
    },
  ],
  'dm-budi': [
    {
      id: 'msg-dm-b-001',
      channelId: 'dm-budi',
      senderId: 'member-002',
      senderName: 'Budi Hartono',
      senderAvatar: 'BH',
      senderRole: 'SPV',
      content: 'Hey Andi, the Gotify integration is looking solid. One thing — should we add a retry mechanism for failed WA deliveries?',
      timestamp: minsAgo(55),
      status: 'read',
      reactions: [],
      isMe: false,
    },
    {
      id: 'msg-dm-b-002',
      channelId: 'dm-budi',
      senderId: 'member-001',
      senderName: 'Andi Susanto',
      senderAvatar: 'AS',
      senderRole: 'Manager',
      content: 'Yes, good idea. Let\'s add 3 retries with exponential backoff on the GoWa side. Can you create a task for it?',
      timestamp: minsAgo(50),
      status: 'read',
      reactions: [],
      isMe: true,
    },
    {
      id: 'msg-dm-b-003',
      channelId: 'dm-budi',
      senderId: 'member-002',
      senderName: 'Budi Hartono',
      senderAvatar: 'BH',
      senderRole: 'SPV',
      content: 'Can you review the RLS PR when you get a chance?',
      timestamp: minsAgo(35),
      status: 'delivered',
      reactions: [],
      isMe: false,
    },
  ],
  'ch-infrastructure': [
    {
      id: 'msg-infra-001',
      channelId: 'ch-infrastructure',
      senderId: 'member-002',
      senderName: 'Budi Hartono',
      senderAvatar: 'BH',
      senderRole: 'SPV',
      content: 'All 4 Docker containers are healthy on Coolify. Next.js, Supabase, GoWa, and Gotify — all green.',
      timestamp: minsAgo(120),
      status: 'read',
      reactions: [{ emoji: '✅', count: 2, byMe: true }],
      isMe: false,
      attachments: [{ name: 'coolify-health-check.pdf', size: '42 KB', type: 'pdf' }],
    },
    {
      id: 'msg-infra-002',
      channelId: 'ch-infrastructure',
      senderId: 'member-001',
      senderName: 'Andi Susanto',
      senderAvatar: 'AS',
      senderRole: 'Manager',
      content: 'Nice. Let\'s schedule a load test for next Tuesday once the RLS changes are in production.',
      timestamp: minsAgo(115),
      status: 'read',
      reactions: [],
      isMe: true,
    },
    {
      id: 'msg-infra-003',
      channelId: 'ch-infrastructure',
      senderId: 'member-002',
      senderName: 'Budi Hartono',
      senderAvatar: 'BH',
      senderRole: 'SPV',
      content: 'Gotify container restarted — all push notifications normal.',
      timestamp: minsAgo(45),
      status: 'read',
      reactions: [],
      isMe: false,
    },
  ],
  'ch-marketing': [
    {
      id: 'msg-mkt-001',
      channelId: 'ch-marketing',
      senderId: 'member-005',
      senderName: 'Eka Wulandari',
      senderAvatar: 'EW',
      senderRole: 'SPV',
      content: 'Q2 Instagram campaign brief is ready. Citra, can you start on the visual assets this week?',
      timestamp: minsAgo(200),
      status: 'read',
      reactions: [],
      isMe: false,
    },
    {
      id: 'msg-mkt-002',
      channelId: 'ch-marketing',
      senderId: 'member-003',
      senderName: 'Citra Dewi',
      senderAvatar: 'CD',
      senderRole: 'Employee',
      content: 'On it! I\'ll have the first batch ready by Wednesday. Instagram assets uploaded to docs folder.',
      timestamp: minsAgo(95),
      status: 'read',
      reactions: [{ emoji: '👏', count: 1, byMe: false }],
      isMe: false,
    },
  ],
  'dm-citra': [
    {
      id: 'msg-dm-c-001',
      channelId: 'dm-citra',
      senderId: 'member-001',
      senderName: 'Andi Susanto',
      senderAvatar: 'AS',
      senderRole: 'Manager',
      content: 'Hey Citra, the mobile onboarding mockups look great. Can you share the Figma link?',
      timestamp: minsAgo(150),
      status: 'read',
      reactions: [],
      isMe: true,
    },
    {
      id: 'msg-dm-c-002',
      channelId: 'dm-citra',
      senderId: 'member-003',
      senderName: 'Citra Dewi',
      senderAvatar: 'CD',
      senderRole: 'Employee',
      content: 'Sure! Here\'s the link: figma.com/teamflow-onboarding-v3. Sent the mockups to your email too.',
      timestamp: minsAgo(130),
      status: 'read',
      reactions: [],
      isMe: false,
    },
  ],
  'dm-hendra': [
    {
      id: 'msg-dm-h-001',
      channelId: 'dm-hendra',
      senderId: 'member-008',
      senderName: 'Hendra Wijaya',
      senderAvatar: 'HW',
      senderRole: 'CEO',
      content: 'Andi, the Q1 numbers are impressive. Great work on the team.',
      timestamp: minsAgo(490),
      status: 'read',
      reactions: [],
      isMe: false,
    },
    {
      id: 'msg-dm-h-002',
      channelId: 'dm-hendra',
      senderId: 'member-001',
      senderName: 'Andi Susanto',
      senderAvatar: 'AS',
      senderRole: 'Manager',
      content: 'Thank you Pak Hendra! The team really stepped up this quarter. Great work on the Q1 targets.',
      timestamp: minsAgo(480),
      status: 'read',
      reactions: [],
      isMe: true,
    },
  ],
};