import { Task, TeamMember } from './taskTypes';

export const mockMembers: TeamMember[] = [
  { id: 'member-001', name: 'Andi Susanto', avatar: 'AS', role: 'manager', department: 'Operations' },
  { id: 'member-002', name: 'Budi Hartono', avatar: 'BH', role: 'spv', department: 'Engineering' },
  { id: 'member-003', name: 'Citra Dewi', avatar: 'CD', role: 'employee', department: 'Design' },
  { id: 'member-004', name: 'Dimas Pratama', avatar: 'DP', role: 'employee', department: 'Engineering' },
  { id: 'member-005', name: 'Eka Wulandari', avatar: 'EW', role: 'spv', department: 'Marketing' },
  { id: 'member-006', name: 'Farhan Rizki', avatar: 'FR', role: 'employee', department: 'Sales' },
  { id: 'member-007', name: 'Gita Permata', avatar: 'GP', role: 'employee', department: 'Finance' },
  { id: 'member-008', name: 'Hendra Wijaya', avatar: 'HW', role: 'ceo', department: 'Executive' },
];

const now = new Date('2026-04-26T09:29:08');
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();
const daysAhead = (d: number) => new Date(now.getTime() + d * 86400000).toISOString();

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Redesign onboarding flow for mobile app',
    description: 'Update the onboarding screens to match new brand guidelines and improve conversion.',
    status: 'in-progress',
    priority: 'high',
    project: 'Mobile App',
    assignee: mockMembers[2],
    createdBy: mockMembers[0],
    dueDate: daysAhead(2),
    createdAt: daysAgo(5),
    subtaskCount: 6,
    subtaskDone: 4,
    waReminder: true,
    tags: ['design', 'mobile'],
    attachmentCount: 3,
    overdue: false,
  },
  {
    id: 'task-002',
    title: 'Fix payment gateway timeout on checkout',
    description: 'Investigate and resolve the 30s timeout issue affecting ~12% of transactions.',
    status: 'under-review',
    priority: 'critical',
    project: 'E-Commerce Platform',
    assignee: mockMembers[3],
    createdBy: mockMembers[1],
    dueDate: daysAgo(1),
    createdAt: daysAgo(8),
    subtaskCount: 3,
    subtaskDone: 3,
    waReminder: true,
    tags: ['backend', 'urgent'],
    attachmentCount: 1,
    overdue: true,
  },
  {
    id: 'task-003',
    title: 'Q2 marketing campaign asset preparation',
    description: 'Create all visual assets for the Q2 Instagram and LinkedIn campaign.',
    status: 'assigned',
    priority: 'medium',
    project: 'Marketing Q2',
    assignee: mockMembers[4],
    createdBy: mockMembers[0],
    dueDate: daysAhead(7),
    createdAt: daysAgo(2),
    subtaskCount: 8,
    subtaskDone: 1,
    waReminder: true,
    tags: ['marketing', 'design'],
    attachmentCount: 0,
    overdue: false,
  },
  {
    id: 'task-004',
    title: 'Monthly financial report — April 2026',
    description: 'Compile and review all departmental budget vs actuals for April.',
    status: 'draft',
    priority: 'high',
    project: 'Finance',
    assignee: mockMembers[6],
    createdBy: mockMembers[7],
    dueDate: daysAhead(4),
    createdAt: daysAgo(1),
    subtaskCount: 4,
    subtaskDone: 0,
    waReminder: false,
    tags: ['finance', 'report'],
    attachmentCount: 2,
    overdue: false,
  },
  {
    id: 'task-005',
    title: 'Set up GoWa WhatsApp microservice on Coolify',
    description: 'Deploy and configure GoWa Docker container, connect to Supabase webhooks.',
    status: 'done',
    priority: 'high',
    project: 'Infrastructure',
    assignee: mockMembers[1],
    createdBy: mockMembers[0],
    dueDate: daysAgo(3),
    createdAt: daysAgo(12),
    subtaskCount: 5,
    subtaskDone: 5,
    waReminder: false,
    tags: ['devops', 'backend'],
    attachmentCount: 0,
    overdue: false,
  },
  {
    id: 'task-006',
    title: 'Sales pipeline review — Surabaya region',
    description: 'Analyze and present the Q1 sales performance data for Surabaya territory.',
    status: 'in-progress',
    priority: 'medium',
    project: 'Sales',
    assignee: mockMembers[5],
    createdBy: mockMembers[0],
    dueDate: daysAgo(2),
    createdAt: daysAgo(10),
    subtaskCount: 2,
    subtaskDone: 1,
    waReminder: true,
    tags: ['sales', 'report'],
    attachmentCount: 1,
    overdue: true,
  },
  {
    id: 'task-007',
    title: 'Implement RLS policies on Supabase user tables',
    description: 'Define and test row-level security for all user-facing tables per role.',
    status: 'in-progress',
    priority: 'critical',
    project: 'Infrastructure',
    assignee: mockMembers[3],
    createdBy: mockMembers[1],
    dueDate: daysAhead(1),
    createdAt: daysAgo(4),
    subtaskCount: 7,
    subtaskDone: 5,
    waReminder: true,
    tags: ['security', 'backend'],
    attachmentCount: 0,
    overdue: false,
  },
  {
    id: 'task-008',
    title: 'Create employee onboarding checklist template',
    description: 'Draft a standardized checklist for new hire orientation in all departments.',
    status: 'assigned',
    priority: 'low',
    project: 'HR',
    assignee: mockMembers[0],
    createdBy: mockMembers[7],
    dueDate: daysAhead(14),
    createdAt: daysAgo(1),
    subtaskCount: 3,
    subtaskDone: 0,
    waReminder: false,
    tags: ['hr', 'process'],
    attachmentCount: 0,
    overdue: false,
  },
  {
    id: 'task-009',
    title: 'Gotify push notification integration test',
    description: 'End-to-end test: task update → Supabase → Gotify → browser push.',
    status: 'under-review',
    priority: 'high',
    project: 'Infrastructure',
    assignee: mockMembers[1],
    createdBy: mockMembers[0],
    dueDate: daysAhead(3),
    createdAt: daysAgo(6),
    subtaskCount: 4,
    subtaskDone: 4,
    waReminder: true,
    tags: ['devops', 'testing'],
    attachmentCount: 2,
    overdue: false,
  },
  {
    id: 'task-010',
    title: 'Design system documentation — component library',
    description: 'Document all reusable components with usage guidelines and code examples.',
    status: 'draft',
    priority: 'low',
    project: 'Mobile App',
    assignee: mockMembers[2],
    createdBy: mockMembers[0],
    dueDate: daysAhead(21),
    createdAt: daysAgo(0),
    subtaskCount: 10,
    subtaskDone: 0,
    waReminder: false,
    tags: ['design', 'docs'],
    attachmentCount: 0,
    overdue: false,
  },
  {
    id: 'task-011',
    title: 'Customer support SLA audit — March responses',
    description: 'Review all March support tickets and flag any SLA breaches.',
    status: 'done',
    priority: 'medium',
    project: 'Customer Success',
    assignee: mockMembers[4],
    createdBy: mockMembers[0],
    dueDate: daysAgo(5),
    createdAt: daysAgo(14),
    subtaskCount: 2,
    subtaskDone: 2,
    waReminder: false,
    tags: ['support', 'audit'],
    attachmentCount: 3,
    overdue: false,
  },
  {
    id: 'task-012',
    title: 'Update API documentation for v2 endpoints',
    description: 'Rewrite the REST API docs for all v2 routes with updated request/response schemas.',
    status: 'in-progress',
    priority: 'medium',
    project: 'E-Commerce Platform',
    assignee: mockMembers[3],
    createdBy: mockMembers[1],
    dueDate: daysAhead(5),
    createdAt: daysAgo(3),
    subtaskCount: 5,
    subtaskDone: 2,
    waReminder: true,
    tags: ['backend', 'docs'],
    attachmentCount: 1,
    overdue: false,
  },
];

export const mockProjects = [
  'Mobile App',
  'E-Commerce Platform',
  'Marketing Q2',
  'Finance',
  'Infrastructure',
  'Sales',
  'HR',
  'Customer Success',
];